version: "3.4"
services:
  web:
    build: .
    container_name: web
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      - redis
  redis:
    image: redislabs/redismod
    container_name: redis
    ports:
      - "6379:6379"
